Trying capture by value in find_ancestors
I'm getting an error on fela/build-kite saying:

    tmol/io/details/compiled/leaf_atoms.hh(46): error:
    An extended __device__ lambda cannot capture variables by reference

which is weird, because this compiles just fine on the A100 I have access
to